### ISSUE TITLE
Stuck on the step of "snv2fasta.py"

### ISSUE THREAD

**Issue by songofbin** [bm2-lab/iTunes#1]
Hi, Stuck on the step of "snv2fasta.py", Can you help me to fix it?
$ python2 bin/snv2fasta.py -i VCF_test/somatic_mutation/test_snv_vep_ann.txt -o VCF_test/netmhc -s test -p database/Protein/human.pep.all.fa
Traceback (most recent call last):
  File "bin/snv2fasta.py", line 90, in <module>
    gene_symbol.append(g_s)
NameError: name 'g_s' is not defined

So I made a small change from

                if sub_ele[0]=="SYMBOL":
                        g_s= sub_ele[1]
        gene_symbol.append(g_s)

to

                if sub_ele[0]=="SYMBOL":
                        g_s= sub_ele[1]
                        gene_symbol.append(g_s)

But get a new error info:
$ python2 bin/snv2fasta.py -i VCF_test/somatic_mutation/test_snv_vep_ann.txt -o VCF_test/netmhc -s test -p database/Protein/human.pep.all.fa
Traceback (most recent call last):
  File "bin/snv2fasta.py", line 109, in <module>
    wt_head='>WT_'+gene_symbol[i]+'_'+ ref_animo_acid[i]+str(pro_change_pos)+ alt_animo_acid[i]+'_'+ref_nucleotide[i]+str(cdna_position[i])+alt_nucleotide[i]+'_'+chrom_pos[i]+'_'+trans_name[i]
IndexError: list index out of range

**Comment by XIAOCHIZI** [comment]
Hi,
Thanks for your comment，feel sorry for the late reply!
This step was utilized to extract gene symbol from VEP annotation result. As we considered that all mutation could be annotated by VEP, so here we just used:

    if sub_ele[0]=="SYMBOL":
                    g_s= sub_ele[1]
    gene_symbol.append(g_s)
The first error you got might resulted from failed VEP annotation of your SNV or indel, you can check you VEP result file to validate it.

As for how to solve this bug，the ”gene symbol“ used here is just an identifier, if the VEP did not contain a ”gene symbol“ in the "EXTRA" field, you can just replace it with a string such as "NA" or other strings.
So I suggest to change the code here like this:
    if sub_ele[0]=="SYMBOL":
                    g_s= sub_ele[1]
    else:
                    g_s= "No symbols" ###or other strings
    gene_symbol.append(g_s)
Hope this helps!

Best,
Chi

**Comment by ChiZhou-SITI** [comment]
Hi,
Thanks for your comment，feel sorry for the late reply!
This step was utilized to extract gene symbol from VEP annotation result. As we considered that all mutation could be annotated by VEP (at least it is true in all the samples we test), so here we just used:

            if sub_ele[0]=="SYMBOL":
                    g_s= sub_ele[1]
    gene_symbol.append(g_s)

The first error you got might result from failed VEP annotation of your SNV or indel, you can check your VEP result file to validate it.

As for how to solve this bug，the ”gene symbol“ used here is just an identifier, if the VEP did not contain a ”gene symbol“ in the "EXTRA" field, you can just replace it with a string such as "NA" or other strings.
So I suggest to change the code here like this:

            if sub_ele[0]=="SYMBOL":
                    g_s= sub_ele[1]
            else:
                    g_s= "No symbols" ###or other strings
    gene_symbol.append(g_s)
Hope this helps!

Best,
Chi

**Comment by songofbin** [comment]
You are right! Thanks!
